name: Hello World Action
on: [push]
jobs: 
    print-hello-world: 
        runs-on: ubuntu-latest
        steps:
          - run: echo "Hello World!!"
          - run: echo "This works!!"
    print-hello-world-two: 
        runs-on: ubuntu-latest
        steps:
          - run: echo "Hello World Second!!"
          - run: echo "This works Second Time!!"