name: Hello World Action
on: [push]
jobs: 
    build-app: 
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - uses: actions/setup-node@v2
          - name: Install node modules
            run: npm i
          - name: Setup Finish
            run: echo "Huraay!!"